// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function ApplyInstall(arg1:string,arg2:boolean):Promise<gui.SourceMutationResult>;

export function ApplyPending(arg1:boolean):Promise<gui.ApplyResult>;

export function ChooseLocalInstall():Promise<gui.InstallDraft>;

export function ClearPending():Promise<gui.ActionResult>;

export function CreateSkillSet(arg1:string,arg2:string,arg3:Array<string>):Promise<gui.SkillSetMutationResult>;

export function DeleteSkillSet(arg1:string):Promise<gui.SkillSetMutationResult>;

export function ExtendSources(arg1:string,arg2:boolean):Promise<gui.SourceMutationResult>;

export function GetSnapshot(arg1:boolean):Promise<gui.Snapshot>;

export function MeasureContextBudgets():Promise<gui.Snapshot>;

export function PrepareGitInstall(arg1:string):Promise<gui.InstallDraft>;

export function PreviewExtend(arg1:string):Promise<gui.ExtendPreview>;

export function PreviewSkillSetToggle(arg1:string,arg2:Array<string>):Promise<gui.SkillSetTogglePreview>;

export function PreviewUninstall(arg1:string):Promise<gui.UninstallPreview>;

export function ReviewInstall(arg1:string,arg2:Array<gui.InstallCellRequest>):Promise<gui.InstallReview>;

export function SetSkillFavorite(arg1:string,arg2:boolean):Promise<gui.FavoriteMutationResult>;

export function ToggleBoth(arg1:string):Promise<gui.ActionResult>;

export function ToggleCell(arg1:string,arg2:string):Promise<gui.ActionResult>;

export function ToggleGroup(arg1:string):Promise<gui.ActionResult>;

export function ToggleGroupScope(arg1:string,arg2:Array<string>):Promise<gui.ActionResult>;

export function ToggleSkillScope(arg1:Array<string>,arg2:Array<string>):Promise<gui.ActionResult>;

export function ToggleSkillSet(arg1:string,arg2:Array<string>):Promise<gui.ActionResult>;

export function ToggleVisible(arg1:Array<string>):Promise<gui.ActionResult>;

export function UndoCell(arg1:string,arg2:string):Promise<gui.ActionResult>;

export function UninstallSource(arg1:string,arg2:string,arg3:boolean):Promise<gui.SourceMutationResult>;

export function UpdateAllSources(arg1:boolean):Promise<gui.SourceMutationResult>;

export function UpdateSkillSet(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<gui.SkillSetMutationResult>;

export function UpdateSource(arg1:string,arg2:boolean):Promise<gui.SourceMutationResult>;
