// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyInstall(arg1, arg2) {
  return window['go']['main']['App']['ApplyInstall'](arg1, arg2);
}

export function ApplyPending(arg1) {
  return window['go']['main']['App']['ApplyPending'](arg1);
}

export function ChooseLocalInstall() {
  return window['go']['main']['App']['ChooseLocalInstall']();
}

export function ClearPending() {
  return window['go']['main']['App']['ClearPending']();
}

export function CreateSkillSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkillSet'](arg1, arg2, arg3);
}

export function DeleteSkillSet(arg1) {
  return window['go']['main']['App']['DeleteSkillSet'](arg1);
}

export function ExtendSources(arg1, arg2) {
  return window['go']['main']['App']['ExtendSources'](arg1, arg2);
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function MeasureContextBudgets() {
  return window['go']['main']['App']['MeasureContextBudgets']();
}

export function PrepareGitInstall(arg1) {
  return window['go']['main']['App']['PrepareGitInstall'](arg1);
}

export function PreviewExtend(arg1) {
  return window['go']['main']['App']['PreviewExtend'](arg1);
}

export function PreviewSkillSetToggle(arg1, arg2) {
  return window['go']['main']['App']['PreviewSkillSetToggle'](arg1, arg2);
}

export function PreviewUninstall(arg1) {
  return window['go']['main']['App']['PreviewUninstall'](arg1);
}

export function ReviewInstall(arg1, arg2) {
  return window['go']['main']['App']['ReviewInstall'](arg1, arg2);
}

export function SetSkillFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetSkillFavorite'](arg1, arg2);
}

export function ToggleBoth(arg1) {
  return window['go']['main']['App']['ToggleBoth'](arg1);
}

export function ToggleCell(arg1, arg2) {
  return window['go']['main']['App']['ToggleCell'](arg1, arg2);
}

export function ToggleGroup(arg1) {
  return window['go']['main']['App']['ToggleGroup'](arg1);
}

export function ToggleGroupScope(arg1, arg2) {
  return window['go']['main']['App']['ToggleGroupScope'](arg1, arg2);
}

export function ToggleSkillScope(arg1, arg2) {
  return window['go']['main']['App']['ToggleSkillScope'](arg1, arg2);
}

export function ToggleSkillSet(arg1, arg2) {
  return window['go']['main']['App']['ToggleSkillSet'](arg1, arg2);
}

export function ToggleVisible(arg1) {
  return window['go']['main']['App']['ToggleVisible'](arg1);
}

export function UndoCell(arg1, arg2) {
  return window['go']['main']['App']['UndoCell'](arg1, arg2);
}

export function UninstallSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['UninstallSource'](arg1, arg2, arg3);
}

export function UpdateAllSources(arg1) {
  return window['go']['main']['App']['UpdateAllSources'](arg1);
}

export function UpdateSkillSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSkillSet'](arg1, arg2, arg3, arg4);
}

export function UpdateSource(arg1, arg2) {
  return window['go']['main']['App']['UpdateSource'](arg1, arg2);
}
